Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'drivers')

# add the general drvers.
src = Split("""
board.c
platform.c
stm32f10x_it.c
led.c
usart.c
""")

# add Ethernet drvers.
if GetDepend('RT_USING_LWIP'):
    src += ['dm9000a.c']

# add SD drvers.
if GetDepend('RT_USING_DFS'):
    if GetDepend('RT_USING_SDIO') == True:
        src += ['stm32f1xx_sd.c']
    else:	
        src += ['sdcard.c']

# add spi driver.
if GetDepend('RT_USING_SPI') == True:
	src += ['stm32f10xx_spi.c']
	src += ['spi_flash_w25qxx.c']

# add Ethernet drvers.
if GetDepend('RT_USING_RTC'):
    src += ['stm32f1_rtc.c']

# add Ethernet drvers.
if GetDepend('RT_USING_RTGUI'):
    src += ['touch.c']
    if rtconfig.RT_USING_LCD_TYPE == 'ILI932X':
        src += ['ili_lcd_general.c']
    elif rtconfig.RT_USING_LCD_TYPE == 'SSD1289':
        src += ['ssd1289.c']

    
CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
